# Generated by Django 4.2.3 on 2023-08-11 14:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import vacation_diaries.photos.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_main', models.ImageField(blank=True, null=True, upload_to='images', validators=[vacation_diaries.photos.validators.max_file_size])),
                ('photo_second', models.ImageField(blank=True, null=True, upload_to='images', validators=[vacation_diaries.photos.validators.max_file_size])),
                ('photo_third', models.ImageField(blank=True, null=True, upload_to='images', validators=[vacation_diaries.photos.validators.max_file_size])),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_date_and_time', models.DateTimeField(auto_now=True)),
                ('total_likes', models.PositiveIntegerField(default=0)),
                ('likes', models.ManyToManyField(related_name='liked_photos', through='photos.Like', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL)),
                ('vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacations.vacation')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='liked_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.photo'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=250, validators=[django.core.validators.MinLengthValidator(10)])),
                ('publication_date_and_time', models.DateTimeField(auto_now_add=True)),
                ('commented_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
